### ISSUE TITLE
Luke created a repo WITH THE SAME NAME as MY REPOSITORY

### ISSUE THREAD

**Issue by riya-dev** [dollaz-official/dollaz-mobile#1]
Luke created a repo WITH THE SAME NAME AS MINE and wants ME to work in THIS one.

And he just said that he is making a new repo for a new edit in the SAME project and IS NOT INVITING ME TO IT (I AM THE ONE WITH INTELLECTUAL PROPERTY RIGHTS AND THE IDEA). I will sue if this is not resolved.

HE JUST CREATED A WORKING LOG IN SCREEN AND IT WORKS AND I ASKED HOW HE DID IT AND HE SAID HE'S NOT TELLING ME.

**Comment by zhuluke1** [comment]
lol

**Comment by riya-dev** [comment]
?? suing. talk to my lawyer.
