### ISSUE TITLE
Annoying little kid won't stop commenting issues after she didn't want to learn how to code with react native

### ISSUE THREAD

**Issue by zhuluke1** [dollaz-official/dollaz-mobile#2]
This random person named riya dev added me as a contributor to my project called dollaz. I pulled from the project and the file route and structure was all messed up. Claimed that .tsx was standard practice as well. Had to finish creating and learning react native on my own as a business major.

**Comment by riya-dev** [comment]
that lrly never happened. i github mog you so shut up kid

**Comment by riya-dev** [comment]
typescript is an industry standard and any opinion contrary to this FACT is incorrect and uneducated. please retake eecs 183.
